name: Build Snowcaller

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests

      # Build with PyInstaller in a single line, with OS-specific separator
      - name: Build executable
        shell: bash  # Force bash for consistency across OSes
        run: |
          pyinstaller --onefile --add-data "art${{ runner.os == 'Windows' && ';' || ':' }}art" --add-data "NPC${{ runner.os == 'Windows' && ';' || ':' }}NPC" --add-data "consumables.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "event.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "gear.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "keyitems.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "lore.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "monster.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "npcs.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "quest.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "skills.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "treasures.json${{ runner.os == 'Windows' && ';' || ':' }}." --add-data "locations.txt${{ runner.os == 'Windows' && ';' || ':' }}." --hidden-import "requests" --name Snowcaller game.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snowcaller-${{ matrix.os }}
          path: dist/Snowcaller*